### ISSUE TITLE
Plugin fails

### ISSUE THREAD

**Issue by morganrcu** [uncbiag/SlicerUniGradICON#1]
Hi folks,

I'm trying to unsuccesfully test the slicer plugin. I have gone throught the installation steps. After failing to register an image pair, I have pressed Reload and Test in the UI, obtaining the error:

Traceback (most recent call last):
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\bin\Python\slicer\util.py", line 3255, in tryWithErrorDisplay
    yield
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\bin\Python\slicer\ScriptedLoadableModule.py", line 265, in onReloadAndTest
    test(msec=int(slicer.app.userSettings().value("Developer/SelfTestDisplayMessageDelay")), **kwargs)
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\bin\Python\slicer\ScriptedLoadableModule.py", line 83, in runTest
    testCase.runTest(**kwargs)
  File "C:/Users/rcilla/apbi/SlicerUniGradICON/UniGradICON/UniGradICON.py", line 547, in runTest
    self.test_UniGradICON()
  File "C:/Users/rcilla/apbi/SlicerUniGradICON/UniGradICON/UniGradICON.py", line 684, in test_UniGradICON
    logic.process(**parameters)
  File "C:/Users/rcilla/apbi/SlicerUniGradICON/UniGradICON/UniGradICON.py", line 441, in process
    fixed_image = sitkUtils.PullVolumeFromSlicer(image['fixed'])
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\bin\Python\sitkUtils.py", line 36, in PullVolumeFromSlicer
    sitkimage = sitk.ReadImage(myNodeFullITKAddress)
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\site-packages\SimpleITK\extra.py", line 384, in ReadImage
    return reader.Execute()
  File "C:\Users\rcilla\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\site-packages\SimpleITK\SimpleITK.py", line 8502, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\SimpleITK\SimpleITK\Code\IO\src\sitkImageReaderBase.cxx:91:
sitk::ERROR: The file "slicer:000001C8234CE1B0#vtkMRMLScalarVolumeNode1" does not exist.

I would say there is a problem with paths in the code. Any idea?

Rodrigo

**Comment by basardemir** [comment]
Hello,

Thank you for trying our extension and creating this issue. We have updated our repository.

Are you still experiencing this issue?
